export {default as Blog} from './bolg/Blog'
export {default as Feature} from './feature/Feature'
export {default as Footar} from './footar/Footar'
export {default as Header} from './header/Header'
export {default as Possibility} from './possibility/Possibility'
export {default as WhatGPT3} from './whatGPT3/WhatGPT3'
